---
- name: Disabling redis
  ansible.builtin.command: dnf module disable redis -y

- name: Enabling redis
  ansible.builtin.command: dnf module enable redis:7 -y

- name: Installing redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: changing redis config
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: disable proctected mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name: starting and enabling redis
  ansible.builtin.service: 
    name: redis
    state: started
    enabled: true

