---

- name: Importing app set up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Importing python role
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: Impoting daemon reload
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
