--- 
- name: Copying rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
    remote_src: true

- name: Installing rabbitmq 
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Starting and Enabling server
  ansible.builtin.service: 
    name: rabbitmq-server
    state: started
    enabled: true

- name: create and provide permissions to user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present