- name: Creating application user
  ansible.builtin.user:
    name: roboshop
    system: true
    shell: /sbin/nologin
    home: /app
    comments: roboshop system user

- name: removing app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: "Deleting {{component}} file"
  ansible.builtin.file:
    path: "/tmp/{{component}}.zip"
    state: absent

- name: Downloading code
  ansible.builtin.get_url:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{component}}-v3.zip"
    dest: "/tmp/{{component}}.zip"

- name: Unzipping code
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: true
      
