---
- name: Importing app set up 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Importing nodejs set up 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml

- name: Importing system reload set Unzipping
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
